### ISSUE TITLE
Cant get year input to work

### ISSUE THREAD

**Issue by leliu1224** [plambe8/SongApp#1]
year input works for valid integer and invalid string, but breaks on blank string; it still writes to the txt file but for some reason reading it back gives exceptions. you have to manually delete the new string in the songsList.txt to get the app to even run again.

**Comment by 0xburn2** [comment]
I fixed it, for now. It will change the empty string to "0" and continue running the code

**Comment by plambe8** [comment]
But just realized that Year must be optional >.>

**Comment by plambe8** [comment]
Will 0 as the no year option suffice? The error is no longer created but I don't know if Sesh will allow that
